### ISSUE TITLE
InvalidCastException - Json conversion - Pricing

### ISSUE THREAD

**Issue by AsyncRob96** [PokemonTCG/pokemon-tcg-sdk-csharp#38] opened 2023-03-04 21:42 UTC
When I try to get some values I get the following exception:

`Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'data[6].tcgplayer.prices.reverseHolofoil.market', line 1, position 13346.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.`

Used version: 2.4.0

**Comment by jaymarvels** [comment] 2023-03-04 21:43
@RobinVangampelaere Do you have an example request you're making?

**Comment by AsyncRob96** [comment] 2023-03-04 21:50
@jaymarvels Yes sorry!

`var cards = (await _pokemonApiClient.GetApiResourceAsync<PokemonTcgSdk.Standard.Infrastructure.HttpClients.Cards.Card>(take, page, SetFilterBuilder.CreateSetFilter().AddId(setId))).Results;`

`take = 250`
`page = 1`
`setId = "dp1"`

**Comment by jaymarvels** [comment] 2023-03-04 21:59
@RobinVangampelaere Thanks, I'll look to debug and fix

**Comment by jaymarvels** [comment] 2023-03-05 00:56
@RobinVangampelaere should be fixed in v2.4.1

**Comment by AsyncRob96** [comment] 2023-03-05 08:07
@jaymarvels I can still replicate the problem in version v2.4.1

`setId: "ecard2"`
`Error converting value {null} to type 'System.Double'. Path 'data[58].tcgplayer.prices.reverseHolofoil.market'`

`setId: "neo3"`
`Error converting value {null} to type 'System.Double'. Path 'data[63].tcgplayer.prices.1stEditionHolofoil.market'`

**Comment by jaymarvels** [comment] 2023-03-05 12:03
@RobinVangampelaere Having a hard time replicating that on 2.4.1 doing

```
var filter = PokemonFilterBuilder.CreatePokemonFilter().AddSetId("neo3");
var page = await pokeClient.GetApiResourceAsync<PokemonCard>(250, 1, filter);
```

Or even 

```
var filter = PokemonFilterBuilder.CreatePokemonFilter().AddId("neo3");
var page = await pokeClient.GetApiResourceAsync<PokemonCard>(250, 1, filter);
```

Doesn't error for me at all, same on ecard2, are you sure you have the right updated library?

**Comment by Serraniel** [comment] 2023-03-05 16:54
I think that might have been a data issue in the API itself. I noticed errors on the pricing as well yesterday; Cardmarket prices had been sent as string in JSON (seems to be fixed now) and also a null issue in neo3 on the tcgplayer pricings.

**Comment by jaymarvels** [comment] 2023-03-05 19:10
If I run the tests against the suggested sets on 2.4.1 there is no errors for me

**Comment by adwoold** [comment] 2023-03-06 22:37
I am also running into this issue when doing a simple name filter.

`var filter = PokemonFilterBuilder.CreatePokemonFilter().AddName("umbreon");`
`var pokemon = await _pokemonClient.GetApiResourceAsync<PokemonCard>(filter);`

Curious if the reason has been found for this yet?

**Comment by AsyncRob96** [comment] 2023-03-07 07:53
@jaymarvels Did some digging and the weird thing is that if I build my project with the Nuget dependency I still get the errors, but if I clone, build and manually copy over the .dll from this project into my own project I do not get the error anymore. 

Could there have been a deployment problem while upgrading the package? Or am I looking over something?

**Comment by jaymarvels** [comment] 2023-03-07 08:53
@RobinVangampelaere  I think you might be onto something as the new filter AddSetId also isn't in the 2.4.1 nuget package. Let me invetigate and see whats going on

**Comment by AsyncRob96** [comment] 2023-04-01 07:53
> @RobinVangampelaere I think you might be onto something as the new filter AddSetId also isn't in the 2.4.1 nuget package. Let me invetigate and see whats going on

@jaymarvels Any updates on this? It works if I build the source project manually and copy over the .dll, but this is not ideal.

**Comment by jaymarvels** [comment] 2023-04-03 13:03
@RobinVangampelaere You're right its not ideal, planning on getting a fix out shortly, bare with me

**Comment by RemyRM** [comment] 2023-04-10 14:12
Can confirm this existing in 2.4.1 running the following filter:

```
PokemonFilterCollection<string, string> filter = new PokemonFilterCollection<string, string>();
filter.AddName("Pikachu");
var cards = await PokeClient.GetApiResourceAsync<PokemonCard>(filter );
```
Some names like "Arcanine" and "Charmander" do work.

`Error converting value {null} to type 'System.Double'. Path 'data[92].tcgplayer.prices.reverseHolofoil.market', line 1, position 172018.`

As Robin pointed out a valid workaround for this is cloning the SDK-csharp repository, building it and reference this self-build dll or overwriting the dll in the output directory of your build. (Copying the "fixed" dll to your output directory can be automated using post-build scripts so you don't have to do it manually)

Thanks for your work Jay, the workaround is easy and automatable so don't lose any sleep over it 👍🏻

**Comment by ahostetter** [comment] 2024-01-26 19:41
Just wondering if this is still being looked at. I am running into this problem on a new project, and want to know if the workaround is the only solution. Was a root cause ever found?

**Comment by jaymarvels** [comment] 2024-02-03 17:21
@ahostetter looks like the nuget package didn't update. Will be pushing a new one today

**Comment by jaymarvels** [comment] 2024-02-03 18:31
@RobinVangampelaere @RemyRM @adwoold new nuget version fix is out, let me know if this solves the issue and I can look to close this

**Comment by ahostetter** [comment] 2024-02-03 19:44
My testing confirms that the new nuget package 2.4.2 is working. I tested with Charizard and Snorlax which were not working before.

**Closed as completed** 2024-02-03 20:53 UTC
Labels: bug

**Comment by RemyRM** [comment] 2024-02-03 21:21
@jaymarvels Can confirm as well that upgrading to 2.4.2 worked flawlessly (tested with Growlithe, pikachu and Charizard which failed previously).

Thank you for your hard work and support!
